document.addEventListener('DOMContentLoaded', function () {
    var options = {
        data: {
            "China": null,
            "Italy": null,
            "Google": null,
            "USA": null,
            "Spain": null,
            "Germany": null,
            "Iran": null,
            "France": null,
            "S. Korea": null,
            "Switzerland": null,
            "UK": null,
            "Netherlands": null,
            "Belgium": null,
            "Norway": null,
            "Sweden": null,
            "Portugal": null,
            "Brazil": null,
            "Canada": null,
            "Denmark": null,
            "Australia": null,
            "Malaysia": null,
            "Turkey": null,
            "Czechia": null,
            "Israel": null,
            "Ireland": null,
            "Luxembourg": null,
            "Ecuador": null,
            "Pakistan": null,
            "Poland": null,
            "Chile": null,
            "Finland": null,
            "Thailand": null,
            "Iceland": null,
            "Indonesia": null,
            "Saudi Arabia": null,
            "Singapore": null,
            "Romania": null,
            "Slovenia": null,
            "India": null,
            "Philippines": null,
            "Russia": null,
            "Bahrain": null,
            "Estonia": null,
            "Hong Kong": null,
            "South Africa": null,
            "Croatia": null,
            "Mexico": null,
            "Lebanon": null,
            "Panama": null,
            "Colombia": null,
            "Argentina": null,
            "Serbia": null,
            "Dominican Republic": null,
            "Algeria": null,
            "Armenia": null,
            "Kuwait": null,
            "Bulgaria": null,
            "Slovakia": null,
            "San Marino": null,
            "Taiwan": null,
            "UAE": null,
            "Latvia": null,
            "Uruguay": null,
            "Costa Rica": null,
            "Hungary": null,
            "Lithuania": null,
            "Bosnia and Herzegovina": null,
            "Morocco": null,
            "North Macedonia": null,
            "Faeroe Islands": null,
            "Andorra": null,
            "Vietnam": null,
            "Jordan": null,
            "Cyprus": null,
            "Moldova": null,
            "Malta": null,
            "Albania": null,
            "Brunei": null,
            "Cambodia": null,
            "Sri Lanka": null,
            "Belarus": null,
            "Burkina Faso": null,
            "Tunisia": null,
            "Ukraine": null,
            "Venezuela": null,
            "Senegal": null,
            "New Zealand": null,
            "Azerbaijan": null,
            "Kazakhstan": null,
            "Palestine": null,
            "Guadeloupe": null,
            "Georgia": null,
            "Trinidad and Tobago": null,
            "Réunion": null,
            "Uzbekistan": null,
            "Afghanistan": null,
            "Cameroon": null,
            "Martinique": null,
            "Liechtenstein": null,
            "Channel Islands": null,
            "DRC": null,
            "Nigeria": null,
            "Mauritius": null,
            "Bangladesh": null,
            "Guam": null,
            "Honduras": null,
            "Bolivia": null,
            "Ghana": null,
            "Puerto Rico": null,
            "Monaco": null,
            "Paraguay": null,
            "Macao": null,
            "Montenegro": null,
            "Guatemala": null,
            "Jamaica": null,
            "Rwanda": null,
            "Guyana": null,
            "French Guiana": null,
            "French Polynesia": null,
            "Gibraltar": null,
            "Kenya": null,   
            "Barbados": null,
            "Ivory Coast": null,
            "Kyrgyzstan": null,
            "Maldives": null,
            "Tanzania": null,
            "Ethiopia": null,
            "Mayotte": null,
            "Mongolia": null,
            "Aruba": null,
            "Seychelles": null,
            "Equatorial Guinea": null,
            "U.S. Virgin Islands": null,
            "Gabon": null,   
            "Isle of Man": null,
            "Saint Martin": null,
            "Congo": null,
            "El Salvador": null,
            "Liberia": null,
            "Madagascar": null,
            "Mauritania": null,
            "Dominica": null,
            "Vatican City": null,
            "Syria": null,
            "Somalia": null,
            "Uganda": null,
            "Suriname": null,   
            "Bahamas": null,
            "Greenland": null,
            "New Caledonia": null,
            "Eswatini": null,
            "Cayman Islands": null,
            "Curaçao": null,
            "Cabo Verde": null,
            "Namibia": null,
            "Zambia": null,
            "Zimbabwe": null,
            "Sudan": null,
            "Angola": null,
            "Benin": null,   
            "Bermuda": null,
            "Bhutan": null,
            "Fiji": null,
            "Guinea": null,
            "Haiti": null,
            "Nicaragua": null,
            "Niger": null,
            "Nepal": null,
            "Montserrat": null,
            "Mozambique": null,
            "Papua New Guinea": null,
            "St. Vincent Grenadines": null,
            "Sint Maarten": null,   
            "Somalia": null,
            "Timor-Leste": null,
            "Cuba": null
          },
          onAutocomplete: function(res){
            findByCountry(res);
            console.log(res);
          }
    };
    var elems = document.querySelectorAll('.autocomplete');
    M.Autocomplete.init(elems, options);    
});